services:
  web:
    build: corpus
    command: gunicorn --pythonpath './corpus' --bind 0.0.0.0:8000 --workers 4 corpus.wsgi
    expose:
      - "8000"
    networks:
      - web_nginx_net
    volumes:
      - ./corpus/:/usr/src/app
      - static_files:/usr/src/app/static

  nginx:
    build: nginx
    restart: always
    depends_on:
      - web
    networks:
      - web_nginx_net
    ports:
      - "80:80"
    volumes:
      - static_files:/etc/nginx/staticfiles

networks:
  web_nginx_net:

volumes:
  static_files:
