name: django-tests

env:
  DJANGO_SECRET: "j69a=@*)h+d2&1hs#mg1a3ubr1g3c##x5gr$3vf9$w73+hqi!_"
  DEBUG: "True"

run-name: ${{ github.actor }} is running Django Tests
on: [pull_request]
jobs:
  run-django-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r corpus/requirements.txt
      - run: python corpus/manage.py test
