name: pre-deployment-test
run-name: ${{ github.actor }} is running Pre Deployment Test
on: [push, pull_request]
jobs:
  run-django-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python corpus/deploy_test.py
